server:
  port: 8849
eureka:
  client:
    service-url:
      defaultZone: http://admin:eurekaServer@localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:  routes:    cultivateWeb:
      path: /cultivateWeb/**
      service-id: cultivateWeb