spring:
  profiles: dev #开发环境
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://admin:eurekaServer@localhost:8761/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
    ip-address: localhost
    instance-id: ${spring.application.name}:${server.port} #指定实例id
