spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wt?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.gmaya.order.entity
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_NULL
      column-underline: true
      logic-delete-value: 1 # 数据库删除字段,1代表删除
      logic-not-delete-value: 0 # 0代表没删除
  banner: false
